package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path"
	"reflect"
	"strings"
	"text/template"

	"tophatdemon.com/total-invasion-ii/engine/scene"
	"tophatdemon.com/total-invasion-ii/engine/scene/comps"
	"tophatdemon.com/total-invasion-ii/game/world"
)

const ITERATOR_FUNCTION_TEMPLATE = `// Code is generated by world_gen_iters.go; DO NOT EDIT!
// This file provides iterators over entities in the game world that can be entirely stack allocated.
// This is a clunkier than function-based iterators but can provide better performance on lower end hardware.
package world

import (
	"tophatdemon.com/total-invasion-ii/engine/scene"
	"tophatdemon.com/total-invasion-ii/engine/scene/comps"
	"github.com/go-gl/mathgl/mgl32"
	"tophatdemon.com/total-invasion-ii/engine/math2/collision"
	"tophatdemon.com/total-invasion-ii/engine/math2"
	"tophatdemon.com/total-invasion-ii/engine/render"
)

/******************************
 * UPDATE AND RENDER FUNCTIONS *
 ******************************/

func (world *World) UpdateStores(deltaTime float32) {
	{{- range .AllStores }}
	world.{{ .Name }}.Update(deltaTime)
	{{- end }}
}

func (world *World) RenderStores(context *render.Context) {
	{{- range .AllStores }}
	world.{{ .Name }}.Render(context)
	{{- end }}
}

func (world *World) TearDownStores() {
	{{- range .AllStores }}
	world.{{ .Name }}.TearDown()
	{{- end }}
}

/*******************************************************
 * ITERATING ENTITIES IMPLEMENTING SPECIFIC INTERFACES *
 *******************************************************/

{{ range .InterfaceIterators }}

{{- $iterName := (print .PluralName "Iter") -}}

type {{ $iterName }} struct {
	{{- range .Stores }}
	iter{{ .Name }} scene.StorageIter[{{ .ElemType }}]
	{{- end }}
	storageIndex int
	capacity int // Maximum number of elements iterated, based on storage size.
}

func (iter *{{ $iterName }}) Next() ({{ .Interface }}, scene.Handle) {
	if iter == nil {
		return nil, scene.Handle{}
	}
	for ; iter.storageIndex < {{ len .Stores }}; iter.storageIndex++ {
		switch iter.storageIndex {
			{{- range $idx, $store := .Stores }}
			case {{ $idx }}:
				item, handle := iter.iter{{ $store.Name }}.Next()
				if item != nil {
					return item, handle
				}
			{{- end }}
		}
	}
	return nil, scene.Handle{}
}

func (iter *{{ $iterName }}) HasNext() bool {
	if iter == nil {
		return false
	}
	for i := range {{ len .Stores }} {
		switch i {
			{{- range $idx, $store := .Stores }}
			case {{ $idx }}:
				if iter.iter{{ $store.Name }}.HasNext() {
					return true
				}
			{{- end }}
		}
	}
	return false
}

func (iter *{{ $iterName }}) Capacity() int {
	return iter.capacity
}

func (world *World) Iter{{ .PluralName }}() {{ $iterName }} {
	capacity := 0
	{{- range .Stores }} 
	capacity += world.{{ .Name }}.Capacity()
	{{- end}}
	return {{ $iterName }} {
		{{- range .Stores }}
		iter{{ .Name }}: world.{{ .Name }}.Iter(),
		{{- end}}
		storageIndex: 0,
		capacity: capacity,
	}
}
{{ end }}

/******************************
 * SPHERE DETECTION ITERATORS *
 ******************************/

{{ range .SphereIterators }}
 
{{- $sphereIterType := (print .PluralName "InSphereIter") -}}

type {{ $sphereIterType }} struct {
	innerIter {{ .IterType }}
	radius    float32
	spherePos mgl32.Vec3
	exception {{ .EntType }}
}

func (iter *{{ $sphereIterType }}) Next() ({{ .EntType }}, scene.Handle) {
	for {
		ent, id := iter.innerIter.Next()
		if ent == nil {
			break
		}
		if ent == iter.exception {
			continue
		}
		body := ent.Body()
		 
		if body.Layer != ColLayerNone && math2.Abs(body.Shape.DistanceFromPoint(body.Position, iter.spherePos)) < iter.radius {
			return ent, id
		}
	}
	return nil, scene.Handle{}
}

func (iter *{{ $sphereIterType }}) HasNext() bool {
	cloneIter := *iter
	ent, _ := cloneIter.Next()
	return ent != nil
}

func (iter *{{ $sphereIterType }}) Capacity() int {
	return iter.innerIter.Capacity()
}

func (world *World) {{ print "Iter" .PluralName "InSphere" }}(spherePos mgl32.Vec3, sphereRadius float32, exception {{ .EntType }}) {{ $sphereIterType }} {
	return {{ $sphereIterType }}{
		innerIter: world.{{ .IterConstructor }}(),
		radius:     sphereRadius,
		spherePos:  spherePos,
		exception:  exception,
	}
}

{{ end }}`

type StorageInfo struct {
	Name     string
	ElemType string
}

type InterfaceIterParams struct {
	Interface  string // Must be qualified with the package name
	PluralName string
	Stores     []StorageInfo
}

type SphereIterParams struct {
	IterType, EntType string // Must be qualified with package name
	PluralName        string
	IterConstructor   string // Method on the world that creates the inner iterator.
}

const (
	WORLD_PKG = "world"
	SCENE_PKG = "scene"
	OUT_PATH  = "./world_iterators.go" // This will be relative to the file in which the go:generate comment is.
)

var verboseFlag bool

func verbosePrintfln(format string, payload ...any) {
	if verboseFlag {
		fmt.Printf(format, payload...)
		fmt.Println()
	}
}

func genIterParamsFor[Interface any](pluralName string) (params InterfaceIterParams) {
	worldType := reflect.TypeFor[world.World]()
	interfaceType := reflect.TypeFor[Interface]()
	storageOpsType := reflect.TypeFor[scene.StorageOps]()

	params = InterfaceIterParams{
		PluralName: pluralName,
		Stores:     make([]StorageInfo, 0, worldType.NumField()),
		Interface:  qualifyTypeName(interfaceType),
	}

	// Find storage fields in the world struct whose inner types implement the interface.
	for f := range worldType.NumField() {
		field := worldType.Field(f)
		if !reflect.PointerTo(field.Type).Implements(storageOpsType) {
			verbosePrintfln("Field %v doesn't implement StorageOps\n", field.Name)
			continue
		}
		storageImplements := reflect.PointerTo(field.Type).Implements(interfaceType) // True if the storage itself is a member of the interface, like with GameMap
		if !storageImplements {
			if !strings.HasPrefix(field.Type.Name(), "Storage") {
				verbosePrintfln("Field %v is not a scene.Storage type. It's type is '%v'\n", field.Name, field.Type.Name())
				continue
			}

			// Get the storage struct's type parameter by looking at its data field.
			dataField, ok := field.Type.FieldByName("data")
			// Check if the pointer to the element type of the slice is a member of the interface.
			if !ok {
				verbosePrintfln("Field %v does not have a data field\n", field.Name)
				continue
			}

			if dataField.Type.Kind() != reflect.Slice {
				verbosePrintfln("Field %v's data field is not a slice, it has reflect.Kind = %v\n", field.Name, dataField.Type.Kind())
				continue
			}

			if !reflect.PointerTo(dataField.Type.Elem()).Implements(interfaceType) {
				verbosePrintfln("Field %v's data element does not implement the interface %v\n", field.Name, interfaceType.Name())
				continue
			}

			params.Stores = append(params.Stores, StorageInfo{
				Name:     field.Name,
				ElemType: qualifyTypeName(dataField.Type.Elem()),
			})
		} else {
			verbosePrintfln("Field %v is itself a member of the interface %v\n", field.Name, interfaceType.Name())
			params.Stores = append(params.Stores, StorageInfo{
				Name:     field.Name,
				ElemType: qualifyTypeName(field.Type),
			})
		}
	}

	return
}

func qualifyTypeName(typ reflect.Type) string {
	pkgName := path.Base(typ.PkgPath())
	if pkgName == "world" {
		return typ.Name()
	}
	return pkgName + "." + typ.Name()
}

func main() {
	flag.BoolVar(&verboseFlag, "verbose", false, "Print debug information about which fields get included in iterators.")
	flag.Parse()

	// Run the template on the collected data
	tmpl := template.Must(template.New("WORLD ITERATOR").Parse(ITERATOR_FUNCTION_TEMPLATE))

	tplParams := struct {
		InterfaceIterators []InterfaceIterParams
		SphereIterators    []SphereIterParams
		AllStores          []StorageInfo
	}{
		InterfaceIterators: []InterfaceIterParams{
			genIterParamsFor[comps.HasBody]("Bodies"),
			genIterParamsFor[world.HasActor]("Actors"),
			genIterParamsFor[world.Linkable]("Linkables"),
		},
		SphereIterators: []SphereIterParams{
			{
				IterType:        "BodiesIter",
				EntType:         "comps.HasBody",
				PluralName:      "Bodies",
				IterConstructor: "IterBodies",
			},
			{
				IterType:        "ActorsIter",
				EntType:         "HasActor",
				PluralName:      "Actors",
				IterConstructor: "IterActors",
			},
			{
				IterType:        "scene.StorageIter[Projectile]",
				EntType:         "*Projectile",
				PluralName:      "Projectiles",
				IterConstructor: "Projectiles.Iter",
			},
		},
		AllStores: genIterParamsFor[any]("").Stores,
	}

	// Create output file
	outFile, err := os.Create(OUT_PATH)
	if err != nil {
		log.Fatal(err)
	}

	err = tmpl.Execute(outFile, tplParams)
	if err != nil {
		log.Fatal(err)
	}

	defer outFile.Close()
}
