// Code is generated by world_gen_iters.go; DO NOT EDIT!
// This file provides iterators over entities in the game world that can be entirely stack allocated.
// This is a clunkier than function-based iterators but can provide better performance on lower end hardware.
package world

import (
	"tophatdemon.com/total-invasion-ii/engine/scene"
	"tophatdemon.com/total-invasion-ii/engine/scene/comps"
	"github.com/go-gl/mathgl/mgl32"
	"tophatdemon.com/total-invasion-ii/engine/math2"
	"tophatdemon.com/total-invasion-ii/engine/render"
)

/******************************
 * UPDATE AND RENDER FUNCTIONS *
 ******************************/

func (world *World) UpdateStores(deltaTime float32) {
	world.Players.Update(deltaTime)
	world.Enemies.Update(deltaTime)
	world.Chickens.Update(deltaTime)
	world.Walls.Update(deltaTime)
	world.Triggers.Update(deltaTime)
	world.Projectiles.Update(deltaTime)
	world.Effects.Update(deltaTime)
	world.Items.Update(deltaTime)
	world.DebugShapes.Update(deltaTime)
	world.Cameras.Update(deltaTime)
	world.MapLayers.Update(deltaTime)
	world.Props.Update(deltaTime)
}

func (world *World) RenderStores(context *render.Context) {
	world.Players.Render(context)
	world.Enemies.Render(context)
	world.Chickens.Render(context)
	world.Walls.Render(context)
	world.Triggers.Render(context)
	world.Projectiles.Render(context)
	world.Effects.Render(context)
	world.Items.Render(context)
	world.DebugShapes.Render(context)
	world.Cameras.Render(context)
	world.MapLayers.Render(context)
	world.Props.Render(context)
}

func (world *World) TearDownStores() {
	world.Players.TearDown()
	world.Enemies.TearDown()
	world.Chickens.TearDown()
	world.Walls.TearDown()
	world.Triggers.TearDown()
	world.Projectiles.TearDown()
	world.Effects.TearDown()
	world.Items.TearDown()
	world.DebugShapes.TearDown()
	world.Cameras.TearDown()
	world.MapLayers.TearDown()
	world.Props.TearDown()
}

/*******************************************************
 * ITERATING ENTITIES IMPLEMENTING SPECIFIC INTERFACES *
 *******************************************************/

type BodiesIter struct {
	iterPlayers scene.StorageIter[Player]
	iterEnemies scene.StorageIter[Enemy]
	iterChickens scene.StorageIter[Chicken]
	iterWalls scene.StorageIter[Wall]
	iterProjectiles scene.StorageIter[Projectile]
	iterItems scene.StorageIter[Item]
	iterProps scene.StorageIter[Prop]
	storageIndex int
	capacity int // Maximum number of elements iterated, based on storage size.
}

func (iter *BodiesIter) Next() (comps.HasBody, scene.Handle) {
	if iter == nil {
		return nil, scene.Handle{}
	}
	for ; iter.storageIndex < 7; iter.storageIndex++ {
		switch iter.storageIndex {
			case 0:
				item, handle := iter.iterPlayers.Next()
				if item != nil {
					return item, handle
				}
			case 1:
				item, handle := iter.iterEnemies.Next()
				if item != nil {
					return item, handle
				}
			case 2:
				item, handle := iter.iterChickens.Next()
				if item != nil {
					return item, handle
				}
			case 3:
				item, handle := iter.iterWalls.Next()
				if item != nil {
					return item, handle
				}
			case 4:
				item, handle := iter.iterProjectiles.Next()
				if item != nil {
					return item, handle
				}
			case 5:
				item, handle := iter.iterItems.Next()
				if item != nil {
					return item, handle
				}
			case 6:
				item, handle := iter.iterProps.Next()
				if item != nil {
					return item, handle
				}
		}
	}
	return nil, scene.Handle{}
}

func (iter *BodiesIter) HasNext() bool {
	if iter == nil {
		return false
	}
	for i := range 7 {
		switch i {
			case 0:
				if iter.iterPlayers.HasNext() {
					return true
				}
			case 1:
				if iter.iterEnemies.HasNext() {
					return true
				}
			case 2:
				if iter.iterChickens.HasNext() {
					return true
				}
			case 3:
				if iter.iterWalls.HasNext() {
					return true
				}
			case 4:
				if iter.iterProjectiles.HasNext() {
					return true
				}
			case 5:
				if iter.iterItems.HasNext() {
					return true
				}
			case 6:
				if iter.iterProps.HasNext() {
					return true
				}
		}
	}
	return false
}

func (iter *BodiesIter) Capacity() int {
	return iter.capacity
}

func (world *World) IterBodies() BodiesIter {
	capacity := 0 
	capacity += world.Players.Capacity() 
	capacity += world.Enemies.Capacity() 
	capacity += world.Chickens.Capacity() 
	capacity += world.Walls.Capacity() 
	capacity += world.Projectiles.Capacity() 
	capacity += world.Items.Capacity() 
	capacity += world.Props.Capacity()
	return BodiesIter {
		iterPlayers: world.Players.Iter(),
		iterEnemies: world.Enemies.Iter(),
		iterChickens: world.Chickens.Iter(),
		iterWalls: world.Walls.Iter(),
		iterProjectiles: world.Projectiles.Iter(),
		iterItems: world.Items.Iter(),
		iterProps: world.Props.Iter(),
		storageIndex: 0,
		capacity: capacity,
	}
}
type ActorsIter struct {
	iterPlayers scene.StorageIter[Player]
	iterEnemies scene.StorageIter[Enemy]
	iterChickens scene.StorageIter[Chicken]
	storageIndex int
	capacity int // Maximum number of elements iterated, based on storage size.
}

func (iter *ActorsIter) Next() (HasActor, scene.Handle) {
	if iter == nil {
		return nil, scene.Handle{}
	}
	for ; iter.storageIndex < 3; iter.storageIndex++ {
		switch iter.storageIndex {
			case 0:
				item, handle := iter.iterPlayers.Next()
				if item != nil {
					return item, handle
				}
			case 1:
				item, handle := iter.iterEnemies.Next()
				if item != nil {
					return item, handle
				}
			case 2:
				item, handle := iter.iterChickens.Next()
				if item != nil {
					return item, handle
				}
		}
	}
	return nil, scene.Handle{}
}

func (iter *ActorsIter) HasNext() bool {
	if iter == nil {
		return false
	}
	for i := range 3 {
		switch i {
			case 0:
				if iter.iterPlayers.HasNext() {
					return true
				}
			case 1:
				if iter.iterEnemies.HasNext() {
					return true
				}
			case 2:
				if iter.iterChickens.HasNext() {
					return true
				}
		}
	}
	return false
}

func (iter *ActorsIter) Capacity() int {
	return iter.capacity
}

func (world *World) IterActors() ActorsIter {
	capacity := 0 
	capacity += world.Players.Capacity() 
	capacity += world.Enemies.Capacity() 
	capacity += world.Chickens.Capacity()
	return ActorsIter {
		iterPlayers: world.Players.Iter(),
		iterEnemies: world.Enemies.Iter(),
		iterChickens: world.Chickens.Iter(),
		storageIndex: 0,
		capacity: capacity,
	}
}
type LinkablesIter struct {
	iterWalls scene.StorageIter[Wall]
	iterTriggers scene.StorageIter[Trigger]
	iterCameras scene.StorageIter[Camera]
	storageIndex int
	capacity int // Maximum number of elements iterated, based on storage size.
}

func (iter *LinkablesIter) Next() (Linkable, scene.Handle) {
	if iter == nil {
		return nil, scene.Handle{}
	}
	for ; iter.storageIndex < 3; iter.storageIndex++ {
		switch iter.storageIndex {
			case 0:
				item, handle := iter.iterWalls.Next()
				if item != nil {
					return item, handle
				}
			case 1:
				item, handle := iter.iterTriggers.Next()
				if item != nil {
					return item, handle
				}
			case 2:
				item, handle := iter.iterCameras.Next()
				if item != nil {
					return item, handle
				}
		}
	}
	return nil, scene.Handle{}
}

func (iter *LinkablesIter) HasNext() bool {
	if iter == nil {
		return false
	}
	for i := range 3 {
		switch i {
			case 0:
				if iter.iterWalls.HasNext() {
					return true
				}
			case 1:
				if iter.iterTriggers.HasNext() {
					return true
				}
			case 2:
				if iter.iterCameras.HasNext() {
					return true
				}
		}
	}
	return false
}

func (iter *LinkablesIter) Capacity() int {
	return iter.capacity
}

func (world *World) IterLinkables() LinkablesIter {
	capacity := 0 
	capacity += world.Walls.Capacity() 
	capacity += world.Triggers.Capacity() 
	capacity += world.Cameras.Capacity()
	return LinkablesIter {
		iterWalls: world.Walls.Iter(),
		iterTriggers: world.Triggers.Iter(),
		iterCameras: world.Cameras.Iter(),
		storageIndex: 0,
		capacity: capacity,
	}
}
type SavablesIter struct {
	iterPlayers scene.StorageIter[Player]
	iterEnemies scene.StorageIter[Enemy]
	iterChickens scene.StorageIter[Chicken]
	iterItems scene.StorageIter[Item]
	storageIndex int
	capacity int // Maximum number of elements iterated, based on storage size.
}

func (iter *SavablesIter) Next() (Saveable, scene.Handle) {
	if iter == nil {
		return nil, scene.Handle{}
	}
	for ; iter.storageIndex < 4; iter.storageIndex++ {
		switch iter.storageIndex {
			case 0:
				item, handle := iter.iterPlayers.Next()
				if item != nil {
					return item, handle
				}
			case 1:
				item, handle := iter.iterEnemies.Next()
				if item != nil {
					return item, handle
				}
			case 2:
				item, handle := iter.iterChickens.Next()
				if item != nil {
					return item, handle
				}
			case 3:
				item, handle := iter.iterItems.Next()
				if item != nil {
					return item, handle
				}
		}
	}
	return nil, scene.Handle{}
}

func (iter *SavablesIter) HasNext() bool {
	if iter == nil {
		return false
	}
	for i := range 4 {
		switch i {
			case 0:
				if iter.iterPlayers.HasNext() {
					return true
				}
			case 1:
				if iter.iterEnemies.HasNext() {
					return true
				}
			case 2:
				if iter.iterChickens.HasNext() {
					return true
				}
			case 3:
				if iter.iterItems.HasNext() {
					return true
				}
		}
	}
	return false
}

func (iter *SavablesIter) Capacity() int {
	return iter.capacity
}

func (world *World) IterSavables() SavablesIter {
	capacity := 0 
	capacity += world.Players.Capacity() 
	capacity += world.Enemies.Capacity() 
	capacity += world.Chickens.Capacity() 
	capacity += world.Items.Capacity()
	return SavablesIter {
		iterPlayers: world.Players.Iter(),
		iterEnemies: world.Enemies.Iter(),
		iterChickens: world.Chickens.Iter(),
		iterItems: world.Items.Iter(),
		storageIndex: 0,
		capacity: capacity,
	}
}


/******************************
 * SPHERE DETECTION ITERATORS *
 ******************************/

type BodiesInSphereIter struct {
	innerIter BodiesIter
	radius    float32
	spherePos mgl32.Vec3
	exception comps.HasBody
}

func (iter *BodiesInSphereIter) Next() (comps.HasBody, scene.Handle) {
	for {
		ent, id := iter.innerIter.Next()
		if ent == nil {
			break
		}
		if ent == iter.exception {
			continue
		}
		body := ent.Body()
		 
		if body.Layers != ColLayerNone && math2.Abs(body.Shape.DistanceFromPoint(body.Position, iter.spherePos)) < iter.radius {
			return ent, id
		}
	}
	return nil, scene.Handle{}
}

func (iter *BodiesInSphereIter) HasNext() bool {
	cloneIter := *iter
	ent, _ := cloneIter.Next()
	return ent != nil
}

func (iter *BodiesInSphereIter) Capacity() int {
	return iter.innerIter.Capacity()
}

func (world *World) IterBodiesInSphere(spherePos mgl32.Vec3, sphereRadius float32, exception comps.HasBody) BodiesInSphereIter {
	return BodiesInSphereIter{
		innerIter: world.IterBodies(),
		radius:     sphereRadius,
		spherePos:  spherePos,
		exception:  exception,
	}
}

type ActorsInSphereIter struct {
	innerIter ActorsIter
	radius    float32
	spherePos mgl32.Vec3
	exception HasActor
}

func (iter *ActorsInSphereIter) Next() (HasActor, scene.Handle) {
	for {
		ent, id := iter.innerIter.Next()
		if ent == nil {
			break
		}
		if ent == iter.exception {
			continue
		}
		body := ent.Body()
		 
		if body.Layers != ColLayerNone && math2.Abs(body.Shape.DistanceFromPoint(body.Position, iter.spherePos)) < iter.radius {
			return ent, id
		}
	}
	return nil, scene.Handle{}
}

func (iter *ActorsInSphereIter) HasNext() bool {
	cloneIter := *iter
	ent, _ := cloneIter.Next()
	return ent != nil
}

func (iter *ActorsInSphereIter) Capacity() int {
	return iter.innerIter.Capacity()
}

func (world *World) IterActorsInSphere(spherePos mgl32.Vec3, sphereRadius float32, exception HasActor) ActorsInSphereIter {
	return ActorsInSphereIter{
		innerIter: world.IterActors(),
		radius:     sphereRadius,
		spherePos:  spherePos,
		exception:  exception,
	}
}

type ProjectilesInSphereIter struct {
	innerIter scene.StorageIter[Projectile]
	radius    float32
	spherePos mgl32.Vec3
	exception *Projectile
}

func (iter *ProjectilesInSphereIter) Next() (*Projectile, scene.Handle) {
	for {
		ent, id := iter.innerIter.Next()
		if ent == nil {
			break
		}
		if ent == iter.exception {
			continue
		}
		body := ent.Body()
		 
		if body.Layers != ColLayerNone && math2.Abs(body.Shape.DistanceFromPoint(body.Position, iter.spherePos)) < iter.radius {
			return ent, id
		}
	}
	return nil, scene.Handle{}
}

func (iter *ProjectilesInSphereIter) HasNext() bool {
	cloneIter := *iter
	ent, _ := cloneIter.Next()
	return ent != nil
}

func (iter *ProjectilesInSphereIter) Capacity() int {
	return iter.innerIter.Capacity()
}

func (world *World) IterProjectilesInSphere(spherePos mgl32.Vec3, sphereRadius float32, exception *Projectile) ProjectilesInSphereIter {
	return ProjectilesInSphereIter{
		innerIter: world.Projectiles.Iter(),
		radius:     sphereRadius,
		spherePos:  spherePos,
		exception:  exception,
	}
}

