// Code generated by game/world/gen_world_iters.go; DO NOT EDIT!
package world

import (
	"tophatdemon.com/total-invasion-ii/engine/scene"
	"tophatdemon.com/total-invasion-ii/engine/scene/comps"
)

func (world *World) BodyIter() func() (comps.HasBody, scene.Handle) {
	iterPlayers := world.Players.Iter()
	iterEnemies := world.Enemies.Iter()
	iterWalls := world.Walls.Iter()
	iterProps := world.Props.Iter()
	iterProjectiles := world.Projectiles.Iter()
	iterGameMap := world.GameMap.Iter()
	return func() (comps.HasBody, scene.Handle) {
		if item, id := iterPlayers(); item != nil {
			return item, id
		}
		if item, id := iterEnemies(); item != nil {
			return item, id
		}
		if item, id := iterWalls(); item != nil {
			return item, id
		}
		if item, id := iterProps(); item != nil {
			return item, id
		}
		if item, id := iterProjectiles(); item != nil {
			return item, id
		}
		if item, id := iterGameMap(); item != nil {
			return item, id
		}
		return nil, scene.Handle{}
	}
}

func (world *World) ActorIter() func() (HasActor, scene.Handle) {
	iterPlayers := world.Players.Iter()
	iterEnemies := world.Enemies.Iter()
	return func() (HasActor, scene.Handle) {
		if item, id := iterPlayers(); item != nil {
			return item, id
		}
		if item, id := iterEnemies(); item != nil {
			return item, id
		}
		return nil, scene.Handle{}
	}
}

func (world *World) LinkableIter() func() (Linkable, scene.Handle) {
	iterTriggers := world.Triggers.Iter()
	return func() (Linkable, scene.Handle) {
		if item, id := iterTriggers(); item != nil {
			return item, id
		}
		return nil, scene.Handle{}
	}
}
